name: myfirstworkflow
on: push
jobs:
    myfirstjob:
      runs-on: ubuntu-latest
      steps:
        - name: My first step
          run: echo "Hello, World!"
    only-on-main-branch:
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      steps:
        - name: Only on main branch
          run: echo "This runs only on the main branch"

