name: Deploy the Code into EC2 Instance
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: prepare the ssh key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r ./mycode/* ec2-user@${{ secrets.EC2_HOST }}:/var/www/html/



     
