name: list of s3 buckets
on: workflow_dispatch
jobs:
  list-buckets:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: configure aws credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
          aws s3 ls
