name: build and push docker image to ecr
on:
  push:
    branches:
      - main
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: configure aws CLI
        run: |
           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
           aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}
      - name: login to ecr repo
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com


      - name: build, tag and push docker image
        run: | 
         IMAGE_TAG="v-${{ github.sha }}"   # ← safe expression
         IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPO }}"
         echo "building image ${IMAGE_URI}:${IMAGE_TAG}"
         docker build -t ${IMAGE_URI}:${IMAGE_TAG} .
         docker tag ${IMAGE_URI}:${IMAGE_TAG} ${IMAGE_URI}:latest
         docker push ${IMAGE_URI}:latest
         docker push ${IMAGE_URI}:v2
      #  docker push ${IMAGE_URI}:${IMAGE_TAG}

      # - name: build, tag and push docker image
      #   run: | 
      #     #IMAGE_TAG="v-$(echo ${{ GITHUB_SHA }} | cut -c1-7)" 
      #     #IMAGE_TAG="v-$(echo ${{ github.sha }} | cut -c1-7)"
      #     IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPO }}"
      #     echo "building image ${IMAGE_URI}:${IMAGE_TAG}"
      #     docker build -t ${IMAGE_URI}:${IMAGE_TAG} .
      #     docker tag ${IMAGE_URI}:${IMAGE_TAG} ${IMAGE_URI}:latest
      #     docker push ${IMAGE_URI}:${IMAGE_TAG}
      #     docker push ${IMAGE_URI}:latest


   
